const S={lat:null,lng:null,cat:'all',q:'',places:[],markers:new Map(),favorites:JSON.parse(localStorage.getItem('frFav')||'[]'),user:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const icon=c=>({cafe:'☕',fastfood:'🍔',japanese:'🍣',bbq:'🥩',hotpot:'🍲',dessert:'🍰',night:'🌙',restaurant:'🍜'}[c]||'🍴');
const esc=x=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
let map;
function toast(x){const t=$('#toast');t.textContent=x;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2300)}
function init(){map=L.map('map',{zoomControl:false}).setView([23.0,120.2],13);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);
$('#locate').onclick=locate;$('#start').onclick=locate;$('#search').onclick=search;$('#q').onkeydown=e=>e.key==='Enter'&&search();$('#random').onclick=random;$('#sort').onchange=render;$('#close').onclick=()=>$('#modal').classList.remove('show');
$$('.chips button').forEach(b=>b.onclick=()=>{$$('.chips button').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.cat=b.dataset.c;S.lat!==null?load():locate()});}
function locate(){if(!navigator.geolocation)return toast('此瀏覽器不支援定位');$('#status').textContent='正在取得你的位置…';navigator.geolocation.getCurrentPosition(p=>{S.lat=p.coords.latitude;S.lng=p.coords.longitude;map.setView([S.lat,S.lng],15);if(S.user)map.removeLayer(S.user);S.user=L.circleMarker([S.lat,S.lng],{radius:8,color:'#fff',weight:3,fillColor:'#ff6135',fillOpacity:1}).addTo(map).bindPopup('你目前的位置');load()},err=>{$('#status').textContent=err.code===1?'定位權限被拒絕，請在瀏覽器設定允許定位。':'定位逾時，請再試一次。';toast('無法取得目前位置')},{enableHighAccuracy:true,timeout:15000,maximumAge:60000})}
function search(){S.q=$('#q').value.trim();S.lat!==null?load():locate()}
async function load(){const r=$('#results');$('#empty').style.display='none';r.innerHTML="<div class='empty' style='min-height:300px'><strong>✦</strong><h3>正在搜尋</h3><p>正在連線取得附近店家。</p></div>";$('#status').textContent='正在搜尋附近美食…';try{const u=new URLSearchParams({lat:S.lat,lng:S.lng,category:S.cat,q:S.q}),res=await fetch('/api/nearby?'+u),d=await res.json();if(!res.ok||!d.success)throw Error(d.message||'搜尋服務暫時無法連線');S.places=d.places||[];$('#status').textContent=S.places.length?`附近找到 ${S.places.length} 間店家`:'附近沒有符合條件的店家';render();markers()}catch(e){console.error(e);r.innerHTML=`<div class='empty' style='min-height:300px'><strong>!</strong><h3>搜尋失敗</h3><p>${esc(e.message||'資料服務暫時無法連線')}</p><button id='retry'>再試一次 →</button></div>`;$('#retry').onclick=load}}
function render(){const r=$('#results'),list=[...S.places].sort((a,b)=>$('#sort').value==='name'?a.name.localeCompare(b.name,'zh-Hant'):a.distanceKm-b.distanceKm);if(!list.length){r.innerHTML="<div class='empty' style='min-height:300px'><strong>⌕</strong><h3>附近沒有找到</h3><p>換個分類或關鍵字再試試。</p></div>";return}r.innerHTML=list.map(p=>{const fav=S.favorites.includes(p.id),d=p.distanceKm<1?Math.round(p.distanceKm*1000)+' m':p.distanceKm.toFixed(1)+' km';return `<div class="place" data-id="${esc(p.id)}"><div class="icon">${icon(p.category)}</div><div class="main"><div class="top"><h3>${esc(p.name)}</h3><button class="heart ${fav?'on':''}" data-f="${esc(p.id)}">${fav?'♥':'♡'}</button></div><div class="meta"><span>📍 ${d}</span><span>${esc(p.cuisine||'美食')}</span></div><div class="addr">${esc(p.address||'地址資料暫無')}</div><div class="actions"><button data-d="${esc(p.id)}">查看</button><a target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lng}">導航</a></div></div></div>`}).join('');$$('[data-d]').forEach(b=>b.onclick=()=>detail(b.dataset.d));$$('[data-f]').forEach(b=>b.onclick=e=>{e.stopPropagation();fav(b.dataset.f)});$$('.place').forEach(c=>c.onclick=e=>{if(e.target.closest('button,a'))return;const p=S.places.find(x=>x.id===c.dataset.id);if(p){map.setView([p.lat,p.lng],17,{animate:true});S.markers.get(p.id)?.openPopup()}})}
function markers(){S.markers.forEach(m=>map.removeLayer(m));S.markers.clear();S.places.forEach(p=>{const m=L.marker([p.lat,p.lng]).addTo(map).bindPopup(`<b>${esc(p.name)}</b><br><small>${p.distanceKm} km</small>`);m.on('click',()=>detail(p.id));S.markers.set(p.id,m)})}
function detail(id){const p=S.places.find(x=>x.id===id);if(!p)return;$('#detail').innerHTML=`<div class="detail-k">NEARBY DISCOVERY</div><h2 class="detail-title">${esc(p.name)}</h2><div class="meta">${icon(p.category)} ${esc(p.cuisine||'美食')}　📍 ${p.distanceKm} km</div><div class="row"><span>地址</span><b>${esc(p.address||'暫無')}</b></div>${p.phone?`<div class="row"><span>電話</span><b>${esc(p.phone)}</b></div>`:''}${p.openingHours?`<div class="row"><span>營業時間</span><b>${esc(p.openingHours)}</b></div>`:''}<div class="detail-actions"><a target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lng}">開始導航</a><button onclick="fav('${esc(p.id)}');detail('${esc(p.id)}')">${S.favorites.includes(p.id)?'取消收藏':'收藏店家'}</button></div>`;$('#modal').classList.add('show')}
function fav(id){S.favorites=S.favorites.includes(id)?S.favorites.filter(x=>x!==id):[...S.favorites,id];localStorage.setItem('frFav',JSON.stringify(S.favorites));render();toast(S.favorites.includes(id)?'已加入收藏 ♥':'已取消收藏')}
function random(){if(!S.places.length)return locate();const p=S.places[Math.floor(Math.random()*S.places.length)];map.setView([p.lat,p.lng],17,{animate:true});S.markers.get(p.id)?.openPopup();detail(p.id)}
document.addEventListener('DOMContentLoaded',init);
